export enum OfferDiscountType { PERCENTAGE = 'PERCENTAGE', FIXED_AMOUNT = 'FIXED_AMOUNT', BOGO = 'BOGO' }
export enum OfferStatus { DRAFT = 'DRAFT', ACTIVE = 'ACTIVE', PAUSED = 'PAUSED', ARCHIVED = 'ARCHIVED' }
export enum OfferCombineMode { EXCLUSIVE = 'EXCLUSIVE', STACKABLE = 'STACKABLE' }
export enum PaymentMethod { CREDIT_CARD = 'CREDIT_CARD', DEBIT_CARD = 'DEBIT_CARD', UPI = 'UPI', NET_BANKING = 'NET_BANKING', WALLET = 'WALLET' }
export enum CardNetwork { VISA = 'VISA', MASTERCARD = 'MASTERCARD', RUPAY = 'RUPAY', AMEX = 'AMEX', DINERS = 'DINERS' }
export enum CouponStatus { ACTIVE = 'ACTIVE', DISABLED = 'DISABLED' }
export enum RedemptionStatus { RESERVED = 'RESERVED', CONFIRMED = 'CONFIRMED', RELEASED = 'RELEASED' }
export enum IneligibilityReason {
  NOT_ACTIVE = 'NOT_ACTIVE',
  NOT_STARTED = 'NOT_STARTED',
  EXPIRED = 'EXPIRED',
  COUPON_REQUIRED = 'COUPON_REQUIRED',
  CINEMA_NOT_ELIGIBLE = 'CINEMA_NOT_ELIGIBLE',
  MOVIE_NOT_ELIGIBLE = 'MOVIE_NOT_ELIGIBLE',
  DAY_NOT_ELIGIBLE = 'DAY_NOT_ELIGIBLE',
  TIME_NOT_ELIGIBLE = 'TIME_NOT_ELIGIBLE',
  MIN_ORDER_NOT_MET = 'MIN_ORDER_NOT_MET',
  USAGE_LIMIT_REACHED = 'USAGE_LIMIT_REACHED',
  CUSTOMER_LIMIT_REACHED = 'CUSTOMER_LIMIT_REACHED',
  PAYMENT_REQUIRED = 'PAYMENT_REQUIRED',
  PAYMENT_NOT_ELIGIBLE = 'PAYMENT_NOT_ELIGIBLE',
  NO_DISCOUNT = 'NO_DISCOUNT',
}
