export enum SystemRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  CINEMA_ADMIN = 'CINEMA_ADMIN',
  CONTENT_MANAGER = 'CONTENT_MANAGER',
  BOX_OFFICE = 'BOX_OFFICE',
  FINANCE_ADMIN = 'FINANCE_ADMIN',
  THEATRE_STAFF = 'THEATRE_STAFF',
  CUSTOMER = 'CUSTOMER',
}
